<<<<<<< HEAD
MAXDEPTH : 3
VERBOSE : true
XOP : 0.7
MAXXO : 15
MUTP : 0.1
MAXMUT : 3
NEWP: 0.5
MAX_NEW: 3
GENSIZE : 30
MAXGEN : 10
RESULT: Report
=======
MAXDEPTH : 3
VERBOSE : true
XOP : 0.7
MAXXO : 15
MUTP : 0.1
MAXMUT : 3
NEWP: 0.5
MAX_NEW: 3
GENSIZE : 30
MAXGEN : 10
RESULT: Report
>>>>>>> e7c4d3f (Added GUI (--gui) and Updated Documentation)
FSET: ERPT