<<<<<<< HEAD
MAXDEPTH : 3
VERBOSE : false
XOP : 0.8
MAXXO : 25
MUTP : 0.1
MAXMUT : 5
NEWP: 0.15
MAXNEW: 7
GENSIZE : 50
MAXGEN : 100
RESULT: Report
=======
MAXDEPTH : 3
VERBOSE : false
XOP : 0.8
MAXXO : 25
MUTP : 0.1
MAXMUT : 5
NEWP: 0.15
MAXNEW: 7
GENSIZE : 50
MAXGEN : 100
RESULT: Report
>>>>>>> e7c4d3f (Added GUI (--gui) and Updated Documentation)
FSET: T